
#configuration
WorkflowPath = os.path.dirname(os.path.realpath(workflow.snakefile))
include: WorkflowPath +'/snakefiles/config.snakefile'
include : WorkflowPath + '/snakefiles/searchgui+pepshaker.snakefile'
#include: WorkflowPath + '/snakefiles/pepGM.snakefile'


#need to install mono for this to work
#rule ConvertSpectratoMGF:
#     input:'{samplename}.raw' or '{samplename}.mzml'
#     output:'{samplename}.mgf'
#     shell:

rule all:
     input:
          expand(ResultsDir + SampleName + '/Prior' +str(Prior)+'/'+ HostName + '_' + ReferenceDBName +'_PepGM_Results_a{alpha}_b{beta}_p'+str(Prior)+'.png',alpha = AlphaRange, beta = BetaRange)
          #DataDirectory + SampleName + '/' + firstTarget +'_proteinCount.png'


rule CreateFactorGraph:
     input: ResultsDir +'{samplename}/{hostname}_{DBname}_Default_PSM_Report.txt'
     output: ResultsDir +'{samplename}/{hostname}_{DBname}_PepGM_graph_p.graphml'
     conda: 'envs/graphenv.yml'
     params:
          samplename = SampleName,
          hostname = HostName,
          DBname = ReferenceDBName,
          targetTaxa = TargetTaxa,
          firstTarget = firstTarget
     shell: 'python3 workflow/scripts/CreatePepGMGraph.py --targetTaxa {params.targetTaxa} --PSM_Report {input} --PeptideMapPath '+DataDirectory+'{params.samplename}/{params.firstTarget}.json --out {output}'

rule RunPepGM:
     input: ResultsDir +'{samplename}/{hostname}_{DBname}_PepGM_graph.graphml'
     output: ResultsDir +'{samplename}/Prior'+str(Prior)+'/'+'{hostname}_{DBname}_PepGM_Results_a{alpha}_b{beta}_p'+str(Prior)+'.csv'
     conda: 'envs/graphenv.yml'
     params:
          samplename = SampleName,
          hostname = HostName,
          DBname = ReferenceDBName,
          targetTaxa = TargetTaxa,
          firstTarget = firstTarget,
          prior = Prior
     shell: 'python3  workflow/scripts/PepGM.py --GraphMLPath {input} --prior {params.prior} --alpha {wildcards.alpha} --beta {wildcards.beta} --out {output}'

rule BarPlotResults:
     input: ResultsDir +'{samplename}/Prior'+str(Prior)+'/'+'{hostname}_{DBname}_PepGM_Results_a{alpha}_b{beta}_p'+str(Prior)+'.csv'
     output: ResultsDir +'{samplename}/Prior'+str(Prior)+'/'+'{hostname}_{DBname}_PepGM_Results_a{alpha}_b{beta}_p'+str(Prior)+'.png'
     conda: 'envs/graphenv.yml'
     params: NumberofResults = TaxaInPlot
     shell: 'python3 workflow/scripts/BarPlotResults.py --ResultsFile {input} --NumberofResults {params.NumberofResults} --out {output}'

#rules only needed for debugging/checking results
rule CountProteinsInJson:
     input: ResultsDir +'{samplename}/{taxonname}.json'
     output : ResultsDir + '{samplename}/{taxonname}_proteinCount.png'
     params : NumberofResults = TaxaInProteinCount
     conda: 'envs/graphenv.yml'
     shell: 'python3 workflow/scripts/CountProteins.py --ResultsFile {input} --NumberofResults {params.NumberofResults} --out {output}'
     


     