APImail: 'ytanja.holstein@bam.de'
APIkey: 'cbd119d8a7d988bc27f5b0a722a7c861f408'
ExperimentName: 'psl'
SampleName: 'cowpox'
HostName: 'human'
ReferenceDBName: 'minRefSeqViral'
ScientificHostName: "'homo sapiens'" 
FilterSpectra: False
AddHostandCrapToDB: True
SamplePath: '/home/fkistner/pepgm/resources/SampleData/spectrafile_PXD014913_cowpox_minimal_example.mgf'
ParametersFile: '/home/fkistner/pepgm/resources/SampleData/parfile_searchgui_PXD014913_cowpox_minimal_example.par'
DataDir: 'resources/SampleData/'
DatabaseDir: 'resources/Database/'
PeptideShaker: '/home/fkistner/pepgm/bin/PeptideShaker-2.2.16/PeptideShaker-2.2.16.jar'
SearchGUI: '/home/fkistner/pepgm/bin/SearchGUI-4.1.23/SearchGUI-4.1.23.jar'
ResourcesDir: 'resources/'
ResultsDir: 'results/'
TaxidMapping: 'taxidMapping/'
searchengines: '-xtandem'
psmFDR: '5.0'
peptideFDR: '5.0'
proteinFDR: '5.0'
TaxaInPlot: 15
Alpha: [0.01,0.05,0.10,0.20,0.40,0.60]
Beta: [0.01,0.05,0.10,0.20,0.40,0.50,0.70]
prior: [0.10,0.30,0.50]
