### CONFIG PANEL ###
APIkey: ''
APImail: ''

### RUN ###
ExperimentName: 'toyExample' # Run name
SampleName: 'cowpox'  # Sample name (subfolder)
ReferenceDBName: 'minimal_refseqViral_for_cowpox' # Reference database name
HostName: 'human' # Host name
ScientificHostName: "'homo sapiens'" # Scientific host
FilterSpectra: False       # Filter host spectra and crap
AddHostandCrapToDB: True   # Add host and crap to the search database (if True, crap.fasta has to be provided)


### INPUT ###
SamplePath: '' # Sample spectra
ParametersFile: '' # Parameter file
DataDir: 'resources/SampleData/' # Sample
DatabaseDir: 'resources/Database/' # Database
PeptideShakerDir : '' # Peptide Shaker
SearchGUIDir: '' # SearchGUI
ResultsDir: 'results/'
ResourcesDir: 'resources/'
TaxidMapping: 'taxidMapping/'

### SEARCH PANEL ###
searchengines: '-xtandem'
peptideFDR: '5'
proteinFDR: '5'
psmFDR: '5'

### PepGM PANEL ###
TaxaInPlot: 15
TaxaInProteinCount: 15
sourceDB: 'all[FILT]'
Alpha: [0.01,0.05,0.1,0.2,0.4,0.6] # Alpha
Beta: [0.01,0.05,0.1,0.2,0.4,0.5,0.7] # Beta
prior: [0.1,0.3,0.5] # prior
