#paths to directories

DataDir: 'resources/SampleData/'
DatabaseDir: 'resources/Databases/'


#PeptideShaker and SearchGUI directories
PeptideShakerDir : '/home/tholstei/repos/PepGM_all/bin/PeptideShaker-2.1.1/'
SearchGUIDir: '/home/tholstei/repos/PepGM_all/bin/SearchGUI-4.1.1-mac_and_linux/SearchGUI-4.1.1/'

#parameters for SearchGUI Search
searchengines: '-xtandem'
peptideFDR: '5'
proteinFDR: '5'
psmFDR: '5'

#sample specific parameters

SpectraFileType: '.mzML' #'.mgf' or '.mzML'
SampleName: 'PXD005104_Herpessimplex_1'  #needs to be the name of your spectrum file and the folder where you have that file
HostName: 'human'
ReferenceDBName: 'refseq'


#PepGM parameters
TaxaInPlot: 15       #how many taxa should appear in the final results barplot
TaxaInProteinCount: 15 #how many taxa should appear in the protein counting barplot
TargetTaxa: '"herpesviridae" "homo sapiens"'
FirstTarget: 'herpesviridae'

Alpha: [0.01,0.05,0.1,0.2,0.4,0.6,0.8] #increments of parameter alpha to use for the grid earch
Beta: [0,0.05,0.1,0.2,0.4,0.5,0.7,0.9] #range of parameter beta to use for the grid search

