APImail: ''
APIkey: ''
ExperimentName: ''
SampleName: ''
HostName: ''
ReferenceDBName: ''
ScientificHostName: ''
FilterSpectra: False
AddHostandCrapToDB: True
SamplePath: ''
ParametersFile: ''
DataDir: 'resources/SampleData/'
DatabaseDir: 'resources/Database/'
PeptideShaker: ''
SearchGUI: ''
ResourcesDir: 'resources/'
ResultsDir: 'results/'
TaxidMapping: 'taxidMapping/'
searchengines:
psmFDR: '5.0'
peptideFDR: '5.0'
proteinFDR: '5.0'
TaxaInPlot: 15
Alpha: [0.01,0.05,0.10,0.20,0.40,0.60]
Beta: [0.01,0.05,0.10,0.20,0.40,0.50,0.70]
prior: [0.10,0.30,0.50]
