### CONFIG PANEL ###
APIkey: '2a1c4ba4755da2d72691d5a6198b22712408'
APImail: 'franziska.kistner@bam.de'

### RUN ###
ExperimentName: 'toy' # Run name
SampleName: 'Cowpox'  # Sample name (subfolder)
ReferenceDBName: 'minimal_refseqViral_for_cowpox' # Reference database name
HostName: 'human' # Host name
ScientificHostName: "'homo sapiens'" # Scientific host
FilterSpectra: False       # Filter host spectra and crap
AddHostandCrapToDB: True   # Add host and crap to the search database (if True, crap.fasta has to be provided)


### INPUT ###
SamplePath: '/home/fkistner/pepgm/resources/toyExample/spectra_PXD014913_cowpox_minimal_example.mgf' # Sample spectra
ParametersFile: '/home/fkistner/pepgm/resources/toyExample/parfile_searchgui_PXD014913_cowpox_minimal_example.par' # Parameter file
DataDir: 'resources/SampleData/' # Sample
DatabaseDir: 'resources/Database/' # Database
PeptideShakerDir : '/home/fkistner/pepgm/bin/PeptideShaker-2.2.9/' # Peptide Shaker
SearchGUIDir: '/home/fkistner/pepgm/bin/SearchGUI-4.1.14/' # SearchGUI
ResultsDir: 'results/'
ResourcesDir: 'resources/'
TaxidMapping: 'taxidMapping/'

### SEARCH PANEL ###
searchengines: '-xtandem'
peptideFDR: '5'
proteinFDR: '5'
psmFDR: '5'

### PepGM PANEL ###
TaxaInPlot: 15
TaxaInProteinCount: 15
sourceDB: 'all[FILT]'
Alpha: [0.01,0.05,0.1,0.2,0.4,0.6] # Alpha
Beta: [0.01,0.05,0.1,0.2,0.4,0.5,0.7] # Beta
prior: [0.1,0.3,0.5] # prior
